# Generated by Django 2.0.7 on 2022-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(blank=True, max_length=25, null=True)),
                ('lname', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('doctor', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pass1', models.CharField(max_length=100)),
            ],
        ),
    ]
