# Generated by Django 2.0.7 on 2022-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0002_remove_patient_mname'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('user', models.CharField(blank=True, max_length=25)),
                ('college', models.CharField(blank=True, max_length=25)),
                ('degree', models.CharField(blank=True, max_length=10)),
                ('cgpa', models.IntegerField(blank=True)),
            ],
        ),
    ]
