# Generated by Django 2.0.7 on 2022-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0003_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
