# Generated by Django 2.0.7 on 2022-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0004_auto_20220513_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='pass1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='cgpa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='college',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='degree',
            field=models.CharField(max_length=10),
        ),
    ]
