# Generated by Django 2.0.7 on 2022-05-15 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0005_auto_20220513_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhistory', models.CharField(default=None, max_length=100)),
                ('prescription', models.CharField(default=None, max_length=100)),
                ('appointments', models.DateField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medera.patient')),
            ],
        ),
    ]
