# Generated by Django 2.0.7 on 2022-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0006_patientrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='mhistory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription',
            field=models.CharField(max_length=100),
        ),
    ]
