# Generated by Django 2.0.7 on 2022-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0007_auto_20220515_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='appointments',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='mhistory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
