# Generated by Django 2.0.7 on 2022-05-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0008_auto_20220515_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
