# Generated by Django 2.0.7 on 2022-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0009_delete_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
