# Generated by Django 2.0.7 on 2022-05-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0011_auto_20220517_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
