# Generated by Django 2.0.7 on 2022-05-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220517_1233'),
        ('medera', '0015_auto_20220522_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='doctor',
            field=models.ForeignKey(default='Devanshu', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors'),
        ),
    ]
