# Generated by Django 2.0.7 on 2022-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0016_patientrecord_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='appointdetails',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
