# Generated by Django 2.0.7 on 2022-05-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220517_1233'),
        ('medera', '0017_patientrecord_appointdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField()),
                ('appoint', models.CharField(default='pending', max_length=12)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medera.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='appointdetails',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='doctor',
        ),
    ]
