# Generated by Django 2.0.7 on 2022-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220517_1233'),
        ('medera', '0018_auto_20220522_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointments',
            new_name='appoint',
        ),
    ]
