# Generated by Django 2.0.7 on 2022-05-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0019_auto_20220522_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
    ]
