# Generated by Django 2.0.7 on 2022-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '0020_remove_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='pay',
            field=models.CharField(default='not booked', max_length=12),
        ),
    ]
