# Generated by Django 2.0.7 on 2022-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('user', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=25)),
                ('degree', models.CharField(max_length=10)),
                ('cgpa', models.IntegerField()),
                ('pass1', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
