# Generated by Django 2.0.7 on 2022-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
