# Generated by Django 2.0.7 on 2022-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctors_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
