# Generated by Django 2.0.7 on 2022-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20220515_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
