# Generated by Django 2.0.7 on 2022-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220517_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
