# Generated by Django 2.0.7 on 2022-05-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '__first__'),
        ('doctor', '0005_auto_20220529_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField()),
                ('appoint', models.CharField(default='pending', max_length=12)),
                ('pay', models.CharField(default='not booked', max_length=12)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medera.patient')),
            ],
        ),
    ]
