# Generated by Django 2.0.7 on 2022-05-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medera', '__first__'),
        ('doctor', '0006_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhistory', models.CharField(max_length=100, null=True)),
                ('prescription', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medera.patient')),
            ],
        ),
    ]
