# Generated by Django 2.0.7 on 2022-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='delete',
            field=models.IntegerField(default=0),
        ),
    ]
