# Generated by Django 2.0.7 on 2022-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_appoint_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='mhistory',
            field=models.CharField(default='Nothing to Show', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription',
            field=models.CharField(default='Nothing to show', max_length=100),
        ),
    ]
