# Generated by Django 2.0.7 on 2022-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20220531_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointment',
            field=models.DateField(),
        ),
    ]
