# Generated by Django 2.0.7 on 2022-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='reclogin',
            name='user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
